name: Deploy to cPanel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql
    
    - name: Install Node dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        fi
    
    - name: Install Composer dependencies
      run: |
        if [ -f composer.json ]; then
          composer install --no-dev --optimize-autoloader
        fi
    
    - name: Create backup folder
      run: |
        BACKUP_DATE=$(date +%Y%m%d_%H%M%S)
        echo "Creating backup folder: backup_$BACKUP_DATE"
        echo "BACKUP_FOLDER=backup_$BACKUP_DATE" >> $GITHUB_ENV
    
    - name: Backup existing files via FTP
      uses: appleboy/ftp-action@v0.1.0
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        port: 21
        script: |
          # Create backup directory
          mkdir backup_${{ env.BACKUP_FOLDER }}
          
          # Move existing files to backup (excluding backup folders)
          ls -la | grep -v "^d.*backup_" | grep -v "^d.*\\.$" | grep -v "^d.*\\.\\.$" | awk '{print $9}' | while read file; do
            if [ "$file" != "" ] && [ "$file" != "backup_${{ env.BACKUP_FOLDER }}" ]; then
              echo "Moving $file to backup_${{ env.BACKUP_FOLDER }}/"
              mv "$file" "backup_${{ env.BACKUP_FOLDER }}/" 2>/dev/null || echo "Could not move $file"
            fi
          done
          
          echo "Backup completed: backup_${{ env.BACKUP_FOLDER }}"
    
    - name: Deploy new files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: ./
        server-dir: /
        timeout: 300000
        log-level: verbose
        exclude: |
          **/README.md
          **/.git/**
          **/.github/**
